---
- name: Bootstrap first k3s control plane node
  hosts: k3s_preprod
  become: true
  vars_files:
    - group_vars/all.yml
  tasks:
    - name: Install k3s with cluster-init
      shell: |
        curl -sfL https://get.k3s.io | \
        INSTALL_K3S_EXEC="server --cluster-init" \
        INSTALL_K3S_VERSION={{ k3s_version }} sh -
      args:
        creates: /etc/systemd/system/k3s.service

- name: Ensure the k3s service is running on all nodes
  hosts: k3s_preprod
  become: true
  tasks:
    - name: Check k3s service status
      systemd:
        name: k3s
        state: started
        enabled: true
