---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - >-
    https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ingressroute.yaml
  - namespace.yaml
patches:
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
    path: custom-argocd-cmd-params.yaml
