---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pihole2-pre
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/AlvaroNieto/homelab
        revision: pre
        directories:
          - path: cluster/apps/pihole2/envs/pre
  template:
    metadata:
      name: pre-pihole2
    spec:
      project: default
      source:
        repoURL: https://github.com/AlvaroNieto/homelab
        targetRevision: pre
        path: cluster/apps/pihole2/envs/pre
      destination:
        namespace: pihole-pre
        server: https://10.1.1.99:6443
      syncPolicy:
        automated: {}
