---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pihole2-all
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/AlvaroNieto/homelab
              revision: main
              directories:
                - path: cluster/apps/pihole2/envs/main
          - git:
              repoURL: https://github.com/AlvaroNieto/homelab
              revision: pre
              directories:
                - path: cluster/apps/pihole2/envs/pre
  template:
    metadata:
      name: "{{revision}}-pihole2"
    spec:
      project: default
      source:
        repoURL: https://github.com/AlvaroNieto/homelab
        targetRevision: "{{revision}}"
        path: "cluster/apps/pihole2/envs/{{revision}}"
      destination:
        server: |
          {{- if eq .revision "pre" }}
          https://10.1.1.99:6443
          {{- else }}
          https://kubernetes.default.svc
          {{- end }}
        namespace: |
          {{- if eq .revision "pre" }}
          pihole-pre
          {{- else }}
          pihole-main
          {{- end }}
      syncPolicy:
        automated: {}
