---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole2
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: 'pihole/pihole:latest'
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: Europe/Madrid
            - name: FTLCONF_webserver_api_password
              valueFrom:
                secretKeyRef:
                  key: password
                  name: pihole-webpassword
            - name: FTLCONF_dns_upstreams
              value: 8.8.8.8;8.8.4.4
          volumeMounts:
            - name: pihole-data
              mountPath: /etc/pihole
            - name: dnsmasq-data
              mountPath: /etc/dnsmasq.d
      volumes:
        - name: pihole-data
          persistentVolumeClaim:
            claimName: pihole-data-pvc
        - name: dnsmasq-data
          emptyDir: {}
