---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-webpassword
  namespace: pihole2
spec:
  encryptedData:
    password: |
      AgBodqds4ICverOLSU+Az6Y5+w8cSHAcA3BceEn6HYqB4CWoZ8dapalXitPZ3aYP2FuDEKFLCwAWF/5H9XNrczz7b6la1RVRzDubf9cxKvPykXFeOyR2+ppW3yu84s6eT1uSC0+v6fbgNc6LOoFeF8+B/TbT+hN06wmf0l/hptBQJ+G0lo5HbN8je3FrJxLBUJckNtQtraKEi6ORyt3dfN3SlX9xnYzni+Tntlm0lAprR32S8R8BuFzR0kWfyv+0ZwG+84nhob73hjLWCQZSLmt+X8afBS4jfNA2ANvqYU1Jfku6GekHryZ6nca8QssgSKHKhoTEWm/BObIDMdO++hXIk6sSb+7vaI80Zus7X1Pu4HMbJVJkDXvufKnqZ0XZZrAsTWuVQRLxgN/So/UIXFLhgEPkd6MAfkZHHo5eEaWfp2Dqemi7oZYt9Vz8cmpU3A7v5GXbmKwiEVcwcZcak6oQbNI1DKgwVGN5PXyhhXhxX3r5hcoeXqaCBpR9E5MwoOHTzpk3JbsezLl4tjXtEF88H29Zmfswp7kBbjFB9KopGQ2uFENMnmw0M9Fgva7qiUVjrRvVr048vdFhxX5b1LR9dsAqSoK6w5gofh4xGOrNr5Exrmrfw8tNPRdzH8c4cYV9HPe+9Rhi70hdoOwOAWfkYK3CLuOKDTg33tZkfirXHoS6jf8udHB2Y9fVPKcYQoDmXpmevC8D
  template:
    metadata:
      creationTimestamp: null
      name: pihole-webpassword
      namespace: pihole2
    type: Opaque
