apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-of-main
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: cluster/apps/app-of-apps/main/
    repoURL: https://github.com/AlvaroNieto/homelab/
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
